import type { Metadata } from 'next';
import { Margarine } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/common/Navbar/Navbar';
import Footer from '@/components/common/Footer/Footer';

const margarine = Margarine({
	weight: '400',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Buy Benson',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={margarine.className}>
				<Navbar />
				<main className="benson-wrapper">{children}</main>
				<Footer />
			</body>
		</html>
	);
}
